name: Update README Daily

on:
  schedule:
    - cron: "37 14 * * *" # Ejecutar todos los días a las 2 AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests library
        run: pip install requests

      - name: Run update script
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.email thomas.molina.s@mail.pucv.cl
          git config --global user.name 'Thomas Molina'
          git add .
          commit_message="Update daily image on $(date +'%Y-%m-%d')"
          git commit -m "$commit_message" || echo "No changes to commit"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
